# Generated by Django 5.0.4 on 2024-04-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
